const canvas = document.getElementById('table');
const ctx = canvas.getContext('2d');
const tableWrap = document.getElementById('tableWrap');
const $ = id => document.getElementById(id);
const controls = { felt:$('felt'), rail:$('rail'), pos:$('cuePos'), posY:$('cuePosY'), angle:$('cueAngle'), power:$('power') };
let W=900,H=475,R=14, selected=0, dragging=null, last=0, bounces=0, pocketed=0, ballInHand=null, shotPlayer=null, firstContact=null;
let cues=[{x:245,y:235,angle:-8,power:54,color:'#f9faf4',name:'CUE A · WHITE',active:true},{x:675,y:235,angle:172,power:50,color:'#ffb54c',name:'CUE B · GOLD',active:true}];
let balls=[];
const pockets=[{x:0,y:0,type:'corner'},{x:W/2,y:0,type:'side'},{x:W,y:0,type:'corner'},{x:0,y:H,type:'corner'},{x:W/2,y:H,type:'side'},{x:W,y:H,type:'corner'}];
function setupCanvas(){const dpr=devicePixelRatio||1;const r=canvas.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
const ballColors={1:'#e9c83d',2:'#256fc1',3:'#d8423c',4:'#704c9f',5:'#ea8c31',6:'#298453',7:'#8b302e',8:'#171b1a',9:'#e9c83d',10:'#256fc1',11:'#d8423c',12:'#704c9f',13:'#ea8c31',14:'#298453',15:'#8b302e'};
function reset(){bounces=0;pocketed=0;ballInHand=null;shotPlayer=null;firstContact=null;balls=[{x:cues[0].x,y:cues[0].y,vx:0,vy:0,r:R,color:'#f9faf4',cue:true,pocket:false}];const rackX=585,rackY=235;let n=1;for(let col=0;col<5;col++)for(let row=0;row<=col;row++){const num=n++,team=num<8?'solids':num===8?'eight':'stripes';balls.push({x:rackX+col*25,y:rackY+(row-col/2)*29,vx:0,vy:0,r:R,color:ballColors[num],num,team,pocket:false})}$('status').textContent='TABLE READY';updateStats()}
function updateStats(){const solids=balls.filter(b=>b.team==='solids'&&!b.pocket).length,stripes=balls.filter(b=>b.team==='stripes'&&!b.pocket).length,eight=balls.find(b=>b.team==='eight');$('bounceCount').textContent=bounces;$('pocketCount').textContent=pocketed;$('solidLeft').textContent=solids;$('stripeLeft').textContent=stripes;$('eightState').textContent=eight?.pocket?'IN':'ON'}
function updateUI(){let c=cues[selected],placeCue=balls[0],canPlace=ballInHand!==null;controls.pos.disabled=!canPlace;controls.posY.disabled=!canPlace;controls.pos.value=Math.round(placeCue.x/W*100);controls.posY.value=Math.round(placeCue.y/H*100);controls.angle.value=Math.round(c.angle);controls.power.value=c.power;$('posOut').textContent=Math.round(placeCue.x/W*100)+'%';$('posYOut').textContent=Math.round(placeCue.y/H*100)+'%';$('angleOut').textContent=Math.round(c.angle)+'°';$('powerOut').textContent=c.power+'%';$('cueName').textContent=canPlace?`BALL IN HAND · ${c.name} PLACES WHITE`:c.name;$('placeBtn').textContent=canPlace?'Lock placement':'Place on table';document.querySelectorAll('.cue-tab').forEach((b,i)=>b.classList.toggle('active',i===selected))}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0e483a';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(225,246,215,.12)';ctx.lineWidth=1;ctx.strokeRect(29,29,W-58,H-58);ctx.beginPath();ctx.arc(W/4,H/2,2,0,7);ctx.arc(3*W/4,H/2,2,0,7);ctx.fillStyle='rgba(225,246,215,.4)';ctx.fill();pockets.forEach(({x,y,type})=>{ctx.beginPath();ctx.arc(x,y,type==='side'?28:31,0,7);ctx.fillStyle='#07100e';ctx.fill();ctx.beginPath();ctx.arc(x,y,type==='side'?19:22,0,7);ctx.fillStyle='#020504';ctx.fill()});drawAim();balls.filter(b=>!b.pocket).forEach(drawBall)}
function drawAim(){let b=balls[0];if(!b||b.pocket||moving())return;let c=cues[selected],a=c.angle*Math.PI/180, x=b.x,y=b.y,dx=Math.cos(a),dy=Math.sin(a);ctx.save();ctx.setLineDash([6,7]);ctx.strokeStyle=c.color;ctx.globalAlpha=.75;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx*650,y+dy*650);ctx.stroke();ctx.restore();ctx.beginPath();ctx.arc(x+dx*(R+8),y+dy*(R+8),3,0,7);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#d7e8d8';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x-dx*115,y-dy*115);ctx.lineTo(x-dx*28,y-dy*28);ctx.stroke();ctx.strokeStyle=c.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-dx*115,y-dy*115);ctx.lineTo(x-dx*28,y-dy*28);ctx.stroke()}
function drawBall(b){ctx.beginPath();ctx.arc(b.x+2,b.y+3,R,0,7);ctx.fillStyle='#06171299';ctx.fill();ctx.beginPath();ctx.arc(b.x,b.y,R,0,7);ctx.fillStyle=b.color;ctx.fill();if(b.team==='stripes'){ctx.beginPath();ctx.arc(b.x,b.y,R*.72,0,7);ctx.fillStyle='#f8f5e8';ctx.fill()}let g=ctx.createRadialGradient(b.x-5,b.y-6,1,b.x,b.y,R);g.addColorStop(0,'#ffffffaa');g.addColorStop(.28,'#ffffff22');g.addColorStop(1,'#00000020');ctx.fillStyle=g;ctx.fill();if(b.num){ctx.beginPath();ctx.arc(b.x,b.y,7,0,7);ctx.fillStyle='#f8f5e8';ctx.fill();ctx.fillStyle='#1b2420';ctx.font='bold 8px DM Mono';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.num,b.x,b.y+.5)}}
function moving(){return balls.some(b=>!b.pocket&&(Math.abs(b.vx)+Math.abs(b.vy)>0.08))}
function verticalPocketOpening(b){return b.y<54||b.y>H-54}
function horizontalPocketOpening(b){return b.x<54||b.x>W-54||Math.abs(b.x-W/2)<39}
function scratchCue(player){if(ballInHand!==null)return;const b=balls[0],opponent=1-player;b.pocket=false;b.vx=b.vy=0;b.x=player===0?165:W-165;b.y=H/2;cues.forEach(c=>{c.x=b.x;c.y=b.y});ballInHand=player;selected=opponent;shotPlayer=null;$('status').textContent=`CUE ${player===0?'A':'B'} SCRATCH — CUE ${opponent===0?'A':'B'} HAS BALL IN HAND`;updateUI()}
function sinkBall(b){if(b.cue){scratchCue(shotPlayer??selected);return}b.pocket=true;b.vx=b.vy=0;pocketed++;if(b.team==='eight'){const solids=balls.some(x=>x.team==='solids'&&!x.pocket),stripes=balls.some(x=>x.team==='stripes'&&!x.pocket);$('status').textContent=(!solids||!stripes)?'8 BALL — TABLE CLEARED':'8 BALL POCKETED EARLY'}else if(b.team)$('status').textContent=`${b.team.toUpperCase()} BALL POCKETED`;updateStats()}
function pocketPhysics(b){
  for(const p of pockets){
    const d=Math.hypot(b.x-p.x,b.y-p.y), capture=p.type==='side'?20:23;
    const dropZone=p.type==='side'?(Math.abs(b.x-p.x)<38&&Math.abs(b.y-p.y)<12):(d<capture||(Math.abs(b.x-p.x)<16&&Math.abs(b.y-p.y)<16));
    if(dropZone){sinkBall(b);return true}
    // The curved leather-facing jaw softly turns near-misses toward or away from the opening.
    if(d<42&&Math.abs(b.vx*(b.x-p.x)/d+b.vy*(b.y-p.y)/d)<Math.hypot(b.vx,b.vy)*.6){const nx=(b.x-p.x)/d,ny=(b.y-p.y)/d,approach=b.vx*nx+b.vy*ny;if(approach<0){b.vx-=approach*nx*1.42;b.vy-=approach*ny*1.42;b.vx*=.78;b.vy*=.78;b.x=p.x+nx*42;b.y=p.y+ny*42;bounces++;updateStats();return true}}
  }
  return false
}
function physics(dt){let friction=.981+Number(controls.felt.value)/100*.014;balls.forEach(b=>{if(b.pocket)return;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=Math.pow(friction,dt);b.vy*=Math.pow(friction,dt);if(Math.abs(b.vx)+Math.abs(b.vy)<.04)b.vx=b.vy=0;if(pocketPhysics(b))return;let rail=Number(controls.rail.value)/100;let hit=false;if(b.x<R&&!verticalPocketOpening(b)){b.x=R;b.vx=Math.abs(b.vx)*rail;hit=true}if(b.x>W-R&&!verticalPocketOpening(b)){b.x=W-R;b.vx=-Math.abs(b.vx)*rail;hit=true}if(b.y<R&&!horizontalPocketOpening(b)){b.y=R;b.vy=Math.abs(b.vy)*rail;hit=true}if(b.y>H-R&&!horizontalPocketOpening(b)){b.y=H-R;b.vy=-Math.abs(b.vy)*rail;hit=true}if(hit&&Math.hypot(b.vx,b.vy)>1){bounces++;updateStats()}});for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let a=balls[i],b=balls[j];if(a.pocket||b.pocket)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d&&d<min){if(a.cue&&b.team){const player=shotPlayer??selected,ownTeam=player===0?'solids':'stripes';if(b.team==='eight'&&balls.some(x=>x.team===ownTeam&&!x.pocket)){scratchCue(player);continue}if(firstContact===null){firstContact=b.team;if(b.team!==ownTeam&&b.team!=='eight'){scratchCue(player);continue}}}let nx=dx/d,ny=dy/d,over=(min-d)/2;a.x-=nx*over;a.y-=ny*over;b.x+=nx*over;b.y+=ny*over;let rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel>0){a.vx-=rel*nx;a.vy-=rel*ny;b.vx+=rel*nx;b.vy+=rel*ny}}}}
function loop(t){let dt=Math.min((t-last)/16.67,2);last=t;if(moving())physics(dt);draw();requestAnimationFrame(loop)}
function shoot(){let b=balls[0],c=cues[selected];if(!b||b.pocket||moving())return;ballInHand=null;shotPlayer=selected;firstContact=null;let a=c.angle*Math.PI/180,s=c.power*.19;b.vx=Math.cos(a)*s;b.vy=Math.sin(a)*s;$('status').textContent='SHOT IN MOTION';updateUI()}
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
canvas.addEventListener('pointerdown',e=>{if(moving())return;let p=point(e),b=balls[0],onBall=Math.hypot(p.x-b.x,p.y-b.y)<34;if(ballInHand!==null&&onBall){dragging='place';canvas.setPointerCapture(e.pointerId);return}if(!b.pocket){dragging='aim';canvas.setPointerCapture(e.pointerId);if(!onBall)updateAim(p)}});function updateAim(p){let b=balls[0],c=cues[selected],dx=p.x-b.x,dy=p.y-b.y;if(!b||Math.hypot(dx,dy)<3)return;c.angle=Math.atan2(dy,dx)*180/Math.PI;controls.angle.value=Math.round(c.angle);$('angleOut').textContent=Math.round(c.angle)+'°'}canvas.addEventListener('pointermove',e=>{if(dragging===null)return;let p=point(e);if(dragging==='aim'){updateAim(p);return}let b=balls[0];b.x=Math.max(R,Math.min(W-R,p.x));b.y=Math.max(R,Math.min(H-R,p.y));cues.forEach(c=>{c.x=b.x;c.y=b.y});controls.pos.value=Math.round(b.x/W*100);controls.posY.value=Math.round(b.y/H*100);$('posOut').textContent=Math.round(b.x/W*100)+'%';$('posYOut').textContent=Math.round(b.y/H*100)+'%'});canvas.addEventListener('pointerup',()=>dragging=null);
controls.felt.oninput=()=>{$('feltOut').textContent=controls.felt.value+'%'};controls.rail.oninput=()=>{$('railOut').textContent=controls.rail.value+'%'};controls.pos.oninput=()=>{let b=balls[0];b.x=controls.pos.value/100*W;cues.forEach(c=>c.x=b.x);$('posOut').textContent=controls.pos.value+'%'};controls.posY.oninput=()=>{let b=balls[0];b.y=controls.posY.value/100*H;cues.forEach(c=>c.y=b.y);$('posYOut').textContent=controls.posY.value+'%'};controls.angle.oninput=()=>{cues[selected].angle=Number(controls.angle.value);$('angleOut').textContent=controls.angle.value+'°'};controls.power.oninput=()=>{cues[selected].power=Number(controls.power.value);$('powerOut').textContent=controls.power.value+'%'};
document.querySelectorAll('.cue-tab').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.cue);updateUI()});$('shootBtn').onclick=shoot;$('resetBtn').onclick=reset;$('placeBtn').onclick=()=>{if(ballInHand!==null){ballInHand=null;$('status').textContent='BALL IN HAND PLACED';updateUI();return}let b=balls[0];b.pocket=false;b.x=cues[selected].x;b.y=cues[selected].y;updateUI()};document.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>{let c=cues[selected];if(b.dataset.shot==='bank'){c.angle=30;c.power=64}else if(b.dataset.shot==='kick'){c.angle=145;c.power=72}else{c.angle=18;c.power=92}updateUI()});window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();shoot()}if(e.key==='r'||e.key==='R')reset();if(e.key==='1'||e.key==='2'){selected=Number(e.key)-1;updateUI()}});window.addEventListener('resize',setupCanvas);setupCanvas();reset();updateUI();requestAnimationFrame(loop);
