const canvas = document.getElementById('table');
const ctx = canvas.getContext('2d');
const tableWrap = document.getElementById('tableWrap');
const $ = id => document.getElementById(id);
const controls = { felt:$('felt'), rail:$('rail'), pos:$('cuePos'), posY:$('cuePosY'), angle:$('cueAngle'), power:$('power') };
let W=900,H=475,R=14,RAIL=30,POCKET_MOUTH=16,CORNER_MOUTH=160, selected=0, dragging=null, last=0, bounces=0, pocketed=0, ballInHand=null, pendingScratch=null, shotPlayer=null, firstContact=null;
let cues=[{x:245,y:235,angle:-8,power:54,color:'#f9faf4',name:'CUE A · WHITE',active:true},{x:675,y:235,angle:172,power:50,color:'#ffb54c',name:'CUE B · GOLD',active:true}];
let balls=[];
// Pocket centres sit beyond the cloth, making each opening visibly recessed into the rail.
const pockets=[{x:-10,y:-10,type:'corner'},{x:W/2,y:-14,type:'side'},{x:W+10,y:-10,type:'corner'},{x:-10,y:H+10,type:'corner'},{x:W/2,y:H+14,type:'side'},{x:W+10,y:H+10,type:'corner'}];
function setupCanvas(){const dpr=devicePixelRatio||1;const r=canvas.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
const ballColors={1:'#e9c83d',2:'#256fc1',3:'#d8423c',4:'#704c9f',5:'#ea8c31',6:'#298453',7:'#8b302e',8:'#171b1a',9:'#e9c83d',10:'#256fc1',11:'#d8423c',12:'#704c9f',13:'#ea8c31',14:'#298453',15:'#8b302e'};
function reset(){bounces=0;pocketed=0;ballInHand=null;pendingScratch=null;shotPlayer=null;firstContact=null;balls=[{x:cues[0].x,y:cues[0].y,vx:0,vy:0,r:R,color:'#f9faf4',cue:true,pocket:false}];const rackX=585,rackY=235,rackRows=[[1],[9,10],[2,8,3],[11,4,12,13],[5,14,6,15,7]];rackRows.forEach((numbers,col)=>numbers.forEach((num,row)=>{const team=num<8?'solids':num===8?'eight':'stripes';balls.push({x:rackX+col*25,y:rackY+(row-col/2)*29,vx:0,vy:0,r:R,color:ballColors[num],num,team,pocket:false})}));$('status').textContent='TABLE READY';updateStats()}
function updateStats(){const solids=balls.filter(b=>b.team==='solids'&&!b.pocket).length,stripes=balls.filter(b=>b.team==='stripes'&&!b.pocket).length,eight=balls.find(b=>b.team==='eight');$('bounceCount').textContent=bounces;$('pocketCount').textContent=pocketed;$('solidLeft').textContent=solids;$('stripeLeft').textContent=stripes;$('eightState').textContent=eight?.pocket?'IN':'ON'}
function updateUI(){let c=cues[selected],placeCue=balls[0],canPlace=ballInHand!==null;controls.pos.disabled=!canPlace;controls.posY.disabled=!canPlace;controls.pos.value=Math.round(placeCue.x/W*100);controls.posY.value=Math.round(placeCue.y/H*100);controls.angle.value=Math.round(c.angle);controls.power.value=c.power;$('posOut').textContent=Math.round(placeCue.x/W*100)+'%';$('posYOut').textContent=Math.round(placeCue.y/H*100)+'%';$('angleOut').textContent=Math.round(c.angle)+'°';$('powerOut').textContent=c.power+'%';$('cueName').textContent=canPlace?`BALL IN HAND · ${c.name} PLACES WHITE`:c.name;$('placeBtn').textContent=canPlace?'Lock placement':'Place on table';document.querySelectorAll('.cue-tab').forEach((b,i)=>b.classList.toggle('active',i===selected))}
function syncCuePlacement(b){cues.forEach(c=>{c.x=b.x;c.y=b.y});controls.pos.value=Math.round(b.x/W*100);controls.posY.value=Math.round(b.y/H*100);$('posOut').textContent=Math.round(b.x/W*100)+'%';$('posYOut').textContent=Math.round(b.y/H*100)+'%'}
function resolveCuePlacement(){if(ballInHand===null)return;const b=balls[0],open=(x,y)=>x>=R&&x<=W-R&&y>=R&&y<=H-R&&balls.every(o=>o===b||o.pocket||Math.hypot(x-o.x,y-o.y)>=b.r+o.r+2);if(!open(b.x,b.y)){const x=b.x,y=b.y;for(let radius=4;radius<Math.max(W,H);radius+=4){let found=false;for(let step=0;step<24;step++){const angle=step/24*Math.PI*2,cx=Math.max(R,Math.min(W-R,x+Math.cos(angle)*radius)),cy=Math.max(R,Math.min(H-R,y+Math.sin(angle)*radius));if(open(cx,cy)){b.x=cx;b.y=cy;found=true;break}}if(found)break}}syncCuePlacement(b)}
function drawRails(){const r=RAIL,s=29,j=6,k=160,c=W/2,paint=points=>{ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();ctx.stroke()};ctx.fillStyle='#0a3d31';ctx.strokeStyle='rgba(179,224,196,.14)';ctx.lineWidth=1;paint([[0,0],[c-s+j,0],[c-s,r],[k,r]]);paint([[W,0],[c+s-j,0],[c+s,r],[W-k,r]]);paint([[0,H],[c-s+j,H],[c-s,H-r],[k,H-r]]);paint([[W,H],[c+s-j,H],[c+s,H-r],[W-k,H-r]]);paint([[0,0],[r,k],[r,H-k],[0,H]]);paint([[W,0],[W-r,k],[W-r,H-k],[W,H]])}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0e483a';ctx.fillRect(0,0,W,H);drawRails();ctx.strokeStyle='rgba(225,246,215,.12)';ctx.lineWidth=1;ctx.strokeRect(RAIL,RAIL,W-RAIL*2,H-RAIL*2);ctx.beginPath();ctx.arc(W/4,H/2,2,0,7);ctx.arc(3*W/4,H/2,2,0,7);ctx.fillStyle='rgba(225,246,215,.4)';ctx.fill();pockets.forEach(({x,y,type})=>{if(type==='corner')return;const outer=23,inner=16,facing=Math.atan2(H/2-y,W/2-x),rim=ctx.createLinearGradient(x-Math.cos(facing)*outer,y-Math.sin(facing)*outer,x+Math.cos(facing)*outer,y+Math.sin(facing)*outer);rim.addColorStop(0,'#28160d');rim.addColorStop(.68,'#85502d');rim.addColorStop(1,'#d0a06a');ctx.beginPath();ctx.arc(x,y,outer,0,7);ctx.fillStyle='#173127';ctx.fill();ctx.beginPath();ctx.arc(x,y,inner,0,7);ctx.fillStyle='#030705';ctx.fill();ctx.strokeStyle=rim;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,outer,0,7);ctx.stroke()});drawAim();balls.filter(b=>!b.pocket).forEach(drawBall)}
function drawAim(){let b=balls[0];if(!b||b.pocket||moving())return;let c=cues[selected],a=c.angle*Math.PI/180, x=b.x,y=b.y,dx=Math.cos(a),dy=Math.sin(a);ctx.save();ctx.setLineDash([6,7]);ctx.strokeStyle=c.color;ctx.globalAlpha=.75;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx*650,y+dy*650);ctx.stroke();ctx.restore();ctx.beginPath();ctx.arc(x+dx*(R+8),y+dy*(R+8),3,0,7);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#d7e8d8';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x-dx*115,y-dy*115);ctx.lineTo(x-dx*28,y-dy*28);ctx.stroke();ctx.strokeStyle=c.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-dx*115,y-dy*115);ctx.lineTo(x-dx*28,y-dy*28);ctx.stroke()}
function drawBall(b){ctx.beginPath();ctx.arc(b.x+2,b.y+3,R,0,7);ctx.fillStyle='#06171299';ctx.fill();ctx.beginPath();ctx.arc(b.x,b.y,R,0,7);ctx.fillStyle=b.color;ctx.fill();if(b.team==='stripes'){ctx.beginPath();ctx.arc(b.x,b.y,R*.72,0,7);ctx.fillStyle='#f8f5e8';ctx.fill()}let g=ctx.createRadialGradient(b.x-5,b.y-6,1,b.x,b.y,R);g.addColorStop(0,'#ffffffaa');g.addColorStop(.28,'#ffffff22');g.addColorStop(1,'#00000020');ctx.fillStyle=g;ctx.fill();if(b.num){ctx.beginPath();ctx.arc(b.x,b.y,7,0,7);ctx.fillStyle='#f8f5e8';ctx.fill();ctx.fillStyle='#1b2420';ctx.font='bold 8px DM Mono';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.num,b.x,b.y+.5)}}
function moving(){return balls.some(b=>!b.pocket&&(Math.abs(b.vx)+Math.abs(b.vy)>0.08))}
function movingTowardPocket(b,p){return (p.x-b.x)*b.vx+(p.y-b.y)*b.vy>0.02}
// A side pocket is entered through its mouth, not by travelling parallel to the rail.
function enteringPocket(b,p){return p.type==='side'?(p.y-b.y)*b.vy>0.02:movingTowardPocket(b,p)}
function cornerPocketOpening(b,p){const left=p.x<W/2,top=p.y<H/2,dx=left?b.x:W-b.x,dy=top?b.y:H-b.y,towardX=left?b.vx<-.02:b.vx>.02,towardY=top?b.vy<-.02:b.vy>.02,ax=Math.abs(b.vx),ay=Math.abs(b.vy),diagonal=Math.min(ax,ay)>Math.max(ax,ay)*.35,jawLimit=RAIL+CORNER_MOUTH+R*2;return dx>=0&&dy>=0&&dx+dy<jawLimit&&towardX&&towardY&&diagonal}
function verticalPocketOpening(b,edge){const candidates=edge===0?[pockets[0],pockets[3]]:[pockets[2],pockets[5]];return candidates.some(p=>cornerPocketOpening(b,p))}
function horizontalPocketOpening(b,edge){const candidates=edge===0?[pockets[0],pockets[1],pockets[2]]:[pockets[3],pockets[4],pockets[5]];return candidates.some(p=>(p.type==='corner'?cornerPocketOpening(b,p):Math.abs(b.x-p.x)<POCKET_MOUTH&&enteringPocket(b,p)))}
function scratchCue(player){if(pendingScratch!==null||ballInHand!==null)return;pendingScratch={player,removed:false};shotPlayer=null;$('status').textContent=`CUE ${player===0?'A':'B'} SCRATCH PENDING — BALLS STILL MOVING`;updateUI()}
function sinkBall(b){if(b.cue){b.pocket=true;b.vx=b.vy=0;scratchCue(shotPlayer??selected);return}b.pocket=true;b.vx=b.vy=0;pocketed++;if(b.team==='eight'){const player=shotPlayer??selected,ownTeam=player===0?'solids':'stripes',ownBallsLeft=balls.some(x=>x.team===ownTeam&&!x.pocket);if(ownBallsLeft){reset();$('status').textContent='8 BALL POCKETED EARLY — TABLE RESET';return}$('status').textContent='8 BALL — TABLE CLEARED'}else if(b.team)$('status').textContent=`${b.team.toUpperCase()} BALL POCKETED`;updateStats()}
function pocketPhysics(b){
  for(const p of pockets){
    const d=Math.hypot(b.x-p.x,b.y-p.y), capture=p.type==='side'?29:32;
    const dropZone=d<capture;
    if(dropZone&&enteringPocket(b,p)){sinkBall(b);return true}
    // The curved leather-facing jaw softly turns near-misses toward or away from the opening.
    if(enteringPocket(b,p)&&d<50&&Math.abs(b.vx*(b.x-p.x)/d+b.vy*(b.y-p.y)/d)<Math.hypot(b.vx,b.vy)*.6){const nx=(b.x-p.x)/d,ny=(b.y-p.y)/d,approach=b.vx*nx+b.vy*ny;if(approach<0){b.vx-=approach*nx*1.42;b.vy-=approach*ny*1.42;b.vx*=.78;b.vy*=.78;bounces++;updateStats();return true}}
  }
  return false
}
function physics(dt){let friction=.981+Number(controls.felt.value)/100*.014;balls.forEach(b=>{if(b.pocket)return;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=Math.pow(friction,dt);b.vy*=Math.pow(friction,dt);if(Math.abs(b.vx)+Math.abs(b.vy)<.04)b.vx=b.vy=0;if(pocketPhysics(b))return;let rail=Number(controls.rail.value)/100,hit=false,min=RAIL+R,maxX=W-RAIL-R,maxY=H-RAIL-R;if(b.x<min&&!verticalPocketOpening(b,0)){b.x=min;b.vx=Math.abs(b.vx)*rail;hit=true}if(b.x>maxX&&!verticalPocketOpening(b,W)){b.x=maxX;b.vx=-Math.abs(b.vx)*rail;hit=true}if(b.y<min&&!horizontalPocketOpening(b,0)){b.y=min;b.vy=Math.abs(b.vy)*rail;hit=true}if(b.y>maxY&&!horizontalPocketOpening(b,H)){b.y=maxY;b.vy=-Math.abs(b.vy)*rail;hit=true}if(hit&&Math.hypot(b.vx,b.vy)>1){bounces++;updateStats()}});for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let a=balls[i],b=balls[j];if(a.pocket||b.pocket)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d&&d<min){if(a.cue&&b.team){const player=shotPlayer??selected,ownTeam=player===0?'solids':'stripes',ownBallsLeft=balls.some(x=>x.team===ownTeam&&!x.pocket);if(b.team==='eight'&&ownBallsLeft)scratchCue(player);if(firstContact===null){firstContact=b.team;if(b.team!==ownTeam&&b.team!=='eight'){scratchCue(player);continue}}}let nx=dx/d,ny=dy/d,over=(min-d)/2;a.x-=nx*over;a.y-=ny*over;b.x+=nx*over;b.y+=ny*over;let rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel>0){a.vx-=rel*nx;a.vy-=rel*ny;b.vx+=rel*nx;b.vy+=rel*ny}}}}
function settleShot(){if(moving())return;if(shotPlayer!==null){const player=shotPlayer;shotPlayer=null;if(firstContact===null){scratchCue(player);return}}if(pendingScratch!==null){const player=pendingScratch.player;if(!pendingScratch.removed){balls[0].pocket=true;pendingScratch.removed=true;return}const opponent=1-player,b=balls[0];pendingScratch=null;b.pocket=false;b.vx=b.vy=0;b.x=player===0?165:W-165;b.y=H/2;ballInHand=player;resolveCuePlacement();selected=opponent;$('status').textContent=`CUE ${player===0?'A':'B'} SCRATCH — CUE ${opponent===0?'A':'B'} HAS BALL IN HAND`;updateUI()}}
function loop(t){let dt=Math.min((t-last)/16.67,2);last=t;if(moving())physics(dt);settleShot();draw();requestAnimationFrame(loop)}
function shoot(){let b=balls[0],c=cues[selected];if(!b||b.pocket||moving())return;ballInHand=null;shotPlayer=selected;firstContact=null;let a=c.angle*Math.PI/180,s=c.power*.19;b.vx=Math.cos(a)*s;b.vy=Math.sin(a)*s;$('status').textContent='SHOT IN MOTION';updateUI()}
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
canvas.addEventListener('pointerdown',e=>{if(moving())return;let p=point(e),b=balls[0],onBall=Math.hypot(p.x-b.x,p.y-b.y)<34;if(ballInHand!==null&&onBall){dragging='place';canvas.setPointerCapture(e.pointerId);return}if(!b.pocket){dragging='aim';canvas.setPointerCapture(e.pointerId);if(!onBall)updateAim(p)}});function updateAim(p){let b=balls[0],c=cues[selected],dx=p.x-b.x,dy=p.y-b.y;if(!b||Math.hypot(dx,dy)<3)return;c.angle=Math.atan2(dy,dx)*180/Math.PI;controls.angle.value=Math.round(c.angle);$('angleOut').textContent=Math.round(c.angle)+'°'}canvas.addEventListener('pointermove',e=>{if(dragging===null)return;let p=point(e);if(dragging==='aim'){updateAim(p);return}let b=balls[0];b.x=Math.max(R,Math.min(W-R,p.x));b.y=Math.max(R,Math.min(H-R,p.y));syncCuePlacement(b)});canvas.addEventListener('pointerup',()=>{if(dragging==='place')resolveCuePlacement();dragging=null});
controls.felt.oninput=()=>{$('feltOut').textContent=controls.felt.value+'%'};controls.rail.oninput=()=>{$('railOut').textContent=controls.rail.value+'%'};controls.pos.oninput=()=>{let b=balls[0];b.x=controls.pos.value/100*W;cues.forEach(c=>c.x=b.x);$('posOut').textContent=controls.pos.value+'%'};controls.posY.oninput=()=>{let b=balls[0];b.y=controls.posY.value/100*H;cues.forEach(c=>c.y=b.y);$('posYOut').textContent=controls.posY.value+'%'};controls.pos.onchange=controls.posY.onchange=resolveCuePlacement;controls.pos.onpointerup=controls.posY.onpointerup=resolveCuePlacement;controls.angle.oninput=()=>{cues[selected].angle=Number(controls.angle.value);$('angleOut').textContent=controls.angle.value+'°'};controls.power.oninput=()=>{cues[selected].power=Number(controls.power.value);$('powerOut').textContent=controls.power.value+'%'};
document.querySelectorAll('.cue-tab').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.cue);updateUI()});$('shootBtn').onclick=shoot;$('resetBtn').onclick=reset;$('placeBtn').onclick=()=>{if(ballInHand!==null){resolveCuePlacement();ballInHand=null;$('status').textContent='BALL IN HAND PLACED';updateUI();return}let b=balls[0];b.pocket=false;b.x=cues[selected].x;b.y=cues[selected].y;updateUI()};document.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>{let c=cues[selected];if(b.dataset.shot==='bank'){c.angle=30;c.power=64}else if(b.dataset.shot==='kick'){c.angle=145;c.power=72}else{c.angle=18;c.power=92}updateUI()});window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();shoot()}if(e.key==='r'||e.key==='R')reset();if(e.key==='1'||e.key==='2'){selected=Number(e.key)-1;updateUI()}});window.addEventListener('resize',setupCanvas);setupCanvas();reset();updateUI();requestAnimationFrame(loop);
