const canvas = document.getElementById('table');
const ctx = canvas.getContext('2d');
const tableWrap = document.getElementById('tableWrap');
const $ = id => document.getElementById(id);
const controls = { felt:$('felt'), rail:$('rail'), pos:$('cuePos'), posY:$('cuePosY'), angle:$('cueAngle'), power:$('power') };
let W=900,H=475,R=14, selected=0, dragging=null, last=0, bounces=0, pocketed=0;
let cues=[{x:245,y:235,angle:-8,power:54,color:'#f9faf4',name:'CUE A · WHITE',active:true},{x:675,y:235,angle:172,power:50,color:'#ffb54c',name:'CUE B · GOLD',active:true}];
let balls=[];
const pockets=[[0,0],[W/2,0],[W,0],[0,H],[W/2,H],[W,H]];
function setupCanvas(){const dpr=devicePixelRatio||1;const r=canvas.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
function reset(){bounces=0;pocketed=0;balls=[];cues.forEach((c,i)=>balls.push({x:c.x,y:c.y,vx:0,vy:0,r:R,color:c.color,cue:i,pocket:false}));const rackX=585,rackY=235;let n=1;for(let col=0;col<5;col++)for(let row=0;row<=col;row++){let colors=['#e9c83d','#256fc1','#d8423c','#704c9f','#ea8c31','#298453','#8b302e','#171b1a','#d8558f','#5b91d4','#f5f0dc','#bb4437','#465b95','#d79225','#8a3a78'];balls.push({x:rackX+col*25,y:rackY+(row-col/2)*29,vx:0,vy:0,r:R,color:colors[(n++-1)%colors.length],num:n-1,pocket:false})}updateStats()}
function updateStats(){$('bounceCount').textContent=bounces;$('pocketCount').textContent=pocketed}
function updateUI(){let c=cues[selected];controls.pos.value=Math.round(c.x/W*100);controls.posY.value=Math.round(c.y/H*100);controls.angle.value=Math.round(c.angle);controls.power.value=c.power;$('posOut').textContent=Math.round(c.x/W*100)+'%';$('posYOut').textContent=Math.round(c.y/H*100)+'%';$('angleOut').textContent=Math.round(c.angle)+'°';$('powerOut').textContent=c.power+'%';$('cueName').textContent=c.name;document.querySelectorAll('.cue-tab').forEach((b,i)=>b.classList.toggle('active',i===selected))}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0e483a';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(225,246,215,.12)';ctx.lineWidth=1;ctx.strokeRect(29,29,W-58,H-58);ctx.beginPath();ctx.arc(W/4,H/2,2,0,7);ctx.arc(3*W/4,H/2,2,0,7);ctx.fillStyle='rgba(225,246,215,.4)';ctx.fill();pockets.forEach(([x,y])=>{ctx.beginPath();ctx.arc(x,y,25,0,7);ctx.fillStyle='#07100e';ctx.fill();ctx.beginPath();ctx.arc(x,y,17,0,7);ctx.fillStyle='#020504';ctx.fill()});drawAim();balls.filter(b=>!b.pocket).forEach(drawBall)}
function drawAim(){let b=balls[selected];if(!b||b.pocket||moving())return;let c=cues[selected],a=c.angle*Math.PI/180, x=b.x,y=b.y,dx=Math.cos(a),dy=Math.sin(a);ctx.save();ctx.setLineDash([6,7]);ctx.strokeStyle=c.color;ctx.globalAlpha=.75;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx*650,y+dy*650);ctx.stroke();ctx.restore();ctx.beginPath();ctx.arc(x+dx*(R+8),y+dy*(R+8),3,0,7);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#d7e8d8';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x-dx*115,y-dy*115);ctx.lineTo(x-dx*28,y-dy*28);ctx.stroke();ctx.strokeStyle=c.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-dx*115,y-dy*115);ctx.lineTo(x-dx*28,y-dy*28);ctx.stroke()}
function drawBall(b){ctx.beginPath();ctx.arc(b.x+2,b.y+3,R,0,7);ctx.fillStyle='#06171299';ctx.fill();ctx.beginPath();ctx.arc(b.x,b.y,R,0,7);ctx.fillStyle=b.color;ctx.fill();let g=ctx.createRadialGradient(b.x-5,b.y-6,1,b.x,b.y,R);g.addColorStop(0,'#ffffffaa');g.addColorStop(.28,'#ffffff22');g.addColorStop(1,'#00000020');ctx.fillStyle=g;ctx.fill();if(b.num){ctx.beginPath();ctx.arc(b.x,b.y,7,0,7);ctx.fillStyle='#f8f5e8';ctx.fill();ctx.fillStyle='#1b2420';ctx.font='bold 8px DM Mono';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.num,b.x,b.y+.5)}}
function moving(){return balls.some(b=>!b.pocket&&(Math.abs(b.vx)+Math.abs(b.vy)>0.08))}
function physics(dt){let friction=.993+Number(controls.felt.value)/100*0.005;balls.forEach(b=>{if(b.pocket)return;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=Math.pow(friction,dt);b.vy*=Math.pow(friction,dt);if(Math.abs(b.vx)+Math.abs(b.vy)<.04)b.vx=b.vy=0;let rail=Number(controls.rail.value)/100;let hit=false;if(b.x<R){b.x=R;b.vx=Math.abs(b.vx)*rail;hit=true}if(b.x>W-R){b.x=W-R;b.vx=-Math.abs(b.vx)*rail;hit=true}if(b.y<R){b.y=R;b.vy=Math.abs(b.vy)*rail;hit=true}if(b.y>H-R){b.y=H-R;b.vy=-Math.abs(b.vy)*rail;hit=true}if(hit&&Math.hypot(b.vx,b.vy)>1){bounces++;updateStats()}for(const [px,py] of pockets)if(Math.hypot(b.x-px,b.y-py)<22){b.pocket=true;b.vx=b.vy=0;pocketed++;updateStats();break}});for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let a=balls[i],b=balls[j];if(a.pocket||b.pocket)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d&&d<min){let nx=dx/d,ny=dy/d,over=(min-d)/2;a.x-=nx*over;a.y-=ny*over;b.x+=nx*over;b.y+=ny*over;let rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel>0){a.vx-=rel*nx;a.vy-=rel*ny;b.vx+=rel*nx;b.vy+=rel*ny}}}}
function loop(t){let dt=Math.min((t-last)/16.67,2);last=t;if(moving())physics(dt);draw();requestAnimationFrame(loop)}
function shoot(){let b=balls[selected],c=cues[selected];if(!b||b.pocket||moving())return;let a=c.angle*Math.PI/180,s=c.power*.19;b.vx=Math.cos(a)*s;b.vy=Math.sin(a)*s;$('status').textContent='SHOT IN MOTION'}
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
canvas.addEventListener('pointerdown',e=>{if(moving())return;let p=point(e);for(let i=0;i<2;i++){let b=balls[i];if(!b.pocket&&Math.hypot(p.x-b.x,p.y-b.y)<32){selected=i;dragging=i;updateUI();canvas.setPointerCapture(e.pointerId);break}}});canvas.addEventListener('pointermove',e=>{if(dragging===null)return;let p=point(e),b=balls[dragging],c=cues[dragging];b.x=c.x=Math.max(R,Math.min(W-R,p.x));b.y=c.y=Math.max(R,Math.min(H-R,p.y));controls.pos.value=Math.round(c.x/W*100);controls.posY.value=Math.round(c.y/H*100);$('posOut').textContent=Math.round(c.x/W*100)+'%';$('posYOut').textContent=Math.round(c.y/H*100)+'%'});canvas.addEventListener('pointerup',()=>dragging=null);
controls.felt.oninput=()=>{$('feltOut').textContent=controls.felt.value+'%'};controls.rail.oninput=()=>{$('railOut').textContent=controls.rail.value+'%'};controls.pos.oninput=()=>{let c=cues[selected],b=balls[selected];c.x=b.x=controls.pos.value/100*W;$('posOut').textContent=controls.pos.value+'%'};controls.posY.oninput=()=>{let c=cues[selected],b=balls[selected];c.y=b.y=controls.posY.value/100*H;$('posYOut').textContent=controls.posY.value+'%'};controls.angle.oninput=()=>{cues[selected].angle=Number(controls.angle.value);$('angleOut').textContent=controls.angle.value+'°'};controls.power.oninput=()=>{cues[selected].power=Number(controls.power.value);$('powerOut').textContent=controls.power.value+'%'};
document.querySelectorAll('.cue-tab').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.cue);updateUI()});$('shootBtn').onclick=shoot;$('resetBtn').onclick=reset;$('placeBtn').onclick=()=>{let b=balls[selected];b.pocket=false;b.x=cues[selected].x;b.y=cues[selected].y};document.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>{let c=cues[selected];if(b.dataset.shot==='bank'){c.angle=30;c.power=64}else if(b.dataset.shot==='kick'){c.angle=145;c.power=72}else{c.angle=18;c.power=92}updateUI()});window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();shoot()}if(e.key==='r'||e.key==='R')reset();if(e.key==='1'||e.key==='2'){selected=Number(e.key)-1;updateUI()}});window.addEventListener('resize',setupCanvas);setupCanvas();reset();updateUI();requestAnimationFrame(loop);
